### ISSUE TITLE
mac os users

### ISSUE THREAD

**Issue by udiNur** [martymac/fpart#11]
hi

I'm using mac os. and I download  fpart following link "http://moo.nac.uci.edu/~hjm/parsync/utils/fpart" 
after I run the following commands ;
```
$ chmod +x fpart
./fpart
```
I getting the following error:
` sh: /usr/local/bin/fpart: cannot execute binary file`

even when I'm trying to do it manually, I get the same thing. 
it seems that fpart don't support on mac os, (even that according to https://github.com/martymac/fpart it should work

> Fpart is primarily developed on FreeBSD.
It has been successfully tested on :
...
Mac OS X (10.6, 10.8)

)

what am I missing?

**Comment by martymac** [comment]
Hello @udiNur,

What you have downloaded is an executable for a GNU/Linux distribution. Please download the source version of fpart and re-build it for Mac OS. Mac OS X is supported and should work out of the box :)

Best regards,

Ganael.

**Comment by martymac** [comment]
I am closing that bug report, please feel free to re-open it if you need additional help.

Best regards,
Ganael.
