### ISSUE TITLE
[REQUEST] Homebrew package for fpart

### ISSUE THREAD

**Issue by kabamwboyer** [martymac/fpart#15]
Would it be possible to [create a homebrew tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for the fpart package to facilitate deployment on MacOS machines, or to allow that work to be done on a separate repo called `homebrew-fpart` so one can use the `brew tap` command? Thanks so much for your time!

**Comment by martymac** [comment]
Hello Wanda,

Unfortunately, I am not a user of Homebrew so I won't be able to create a tap for fpart. Anyway, I would be happy to integrate it if someone provided one to me :)

Anyone interested in contributing ?

**Comment by martymac** [comment]
Hello Wanda,

Good news, thanks for your contribution :)

1. Maybe you can trigger a simple 'fpart -V' which displays the current version as well as build options ?

2. Yes, I presume you can, fpart does not use CMake at all

Once you have everything ready (and if you want), just tell me, I'll import your work into the contribs/package/homebrew directory.

Thanks again :)

**Comment by martymac** [comment]
Hello Wanda,

You can use that simple one-liner :

`touch "${HOME}/.fpart-test" && fpart -n 1 -y ".fpart-test" "${HOME}" 2>/dev/null | grep -q "0 (0): ${HOME}/.fpart-test"`

that will create an empty file in ${HOME} and then use fpart to pack it in a single partition. That will ensure that fpart works, can crawl the filesystrem and output a partition.

Best regards,
Ganael.

**Comment by kabamwboyer** [comment]
Hey Ganael, I've got a quick question for you: when I try to run `fpart` in the terminal as you have described, i.e. 

```touch "${HOME}/.fpart-test" && fpart -n 1 -y ".fpart-test" "${HOME}" 2>/dev/null | grep -q "0 (0): ${HOME}/.fpart-test"```

The command hangs. I attempted to break it apart and test, and observed that 

```fpart -n 1 -y ".fpart-test" "${HOME}"```

gives no output, despite the file `.fpart-test` existing in the home directory. I thought perhaps it was because the point you were attempting to create the partition at, i.e. `${HOME}`, might be problematic, so I did `mkdir ${HOME}/tmpDir` and attempted to run

```fpart -n 1 -y ".fpart-test" "${HOME}/tmpDir"```

The command executed, but no output was forthcoming, and `~/tmpDir` was empty. 

Is there an issue because I'm not using `fpart` correctly as per its usage:

```Usage: fpart [OPTIONS] -n num | -f files | -s size [FILE or DIR...]```

**Comment by martymac** [comment]
Hello Wanda,

Weird... You are using fpart the right way.

Can you add verbose options to see what's happening? :

`$ fpart -vv -n 1 -y ".fpart-test" "${HOME}/tmpDir"`

Maybe you can also try using a fixed directory first, such as /tmp instead of ${HOME}.

Hope this helps,
Regards,

Ganael.

**Comment by kabamwboyer** [comment]
Here ya go, Ganael!

```
$ pwd
/Users/wboyer

$ echo ${HOME}
/Users/wboyer

$ ls -lahe .fpart-test 
-rw-r--r--  1 wboyer  CORP\Domain Users     0B 28 Aug 17:02 .fpart-test

$ fpart -vv -n 1 -y ".fpart-test" "${HOME}/tmpDir"
Examining filesystem...
0 file(s) found.

$ ls -lahe ~/tmpDir/
total 0
drwxr-xr-x   2 wboyer  CORP\Domain Users    64B 29 Aug 09:12 .
drwxr-xr-x@ 84 wboyer  CORP\Domain Users   2.6K 29 Aug 09:12 ..
 0: group:everyone deny delete
```

So I'm not sure if it's actually creating the partition... Should I create a separate bug report and poke around at this later today?

**Comment by martymac** [comment]
Hello Wanda,

Your .fpart-test file is in "${HOME}" while you are asking fpart to work on "${HOME}/tmpDir".

Either move .fpart-test to "${HOME}/tmpDir" or start fpart that way :

`$ fpart -vv -n 1 -y ".fpart-test" "${HOME}"`

It should now find the .fpart-test file and display (on stdout) a single partition with that file inside.

Best regards,

Ganael.

**Comment by kabamwboyer** [comment]
Oh gosh I'm so sorry! I don't know how `fpart` works - only have used your `fpsync`!!! Thank you for walking me through this :D

**Comment by martymac** [comment]
Great, good news :)

**Comment by martymac** [comment]
Hello Wanda,

Is everything working fine regarding that issue ? Is the homebrew package working now or do you still need help ?

Ganael.

**Comment by kabamwboyer** [comment]
Hey @martymac ! Sorry for the delay; things have been a bit crazy at work, and since the needs of the project went in another direction, I haven't taken time on my own to get this working and tested... I'll keep you posted next week if I can eke some time for this task!

**Comment by martymac** [comment]
Hello Wanda,

OK, no pb :) Thanks for the update !

Best regards,

Ganael.

**Comment by martymac** [comment]
I'll close that bur report for now, feel free to re-open it if necessary.

**Comment by benstiglitz** [comment]
FYI, I took a stab at this: https://github.com/Homebrew/homebrew-core/pull/62573/.

**Comment by martymac** [comment]
Hello @benstiglitz,

Good news, thanks!

**Comment by martymac** [comment]
@kabamwboyer, @benstiglitz,

Thanks again for your contribution!
