### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by survient** [martymac/fpart#18]
It looks like there have been several changes since the last minor release and I see that some commits were made to the RPM to mark it as "1.2.0" even though there hasn't been an equivalent git tag added. I'd like to submit some pull requests to the RPM spec file to reflect my own changes and then push new releases to the Fedora/EPEL builds I maintain but first I need a new release on here to be tagged.

**Comment by martymac** [comment]
Hello @survient survient,

Yes, I've received a pull request to update the RPM to the current (devel) version, mostly related to the instructions added to build it.

I am still working on a few modifications that I would like to include in 1.2.0, so please be patient :p

Meanwhile, if you have other modifications to submit for the spec file, do not hesitate to send them, I'll be happy to merge the request. The spec file will then be finalized for 1.2.0 once it is out...

Does that sound OK to you ?

Best regards,
Ganael.

**Comment by survient** [comment]
Sounds excellent, I'll go ahead and review the current spec file and submit a pull request with any revisions I would recommend.

**Comment by martymac** [comment]
Great, thanks :)

**Comment by martymac** [comment]
Hello @survient, happy new year!

Just a few words to announce that Fpart 1.2.0 is out :)

Best regards,

Ganael.

**Comment by survient** [comment]
Thanks @martymac, happy new year to you as well. Fpart 1.2.0 has been packaged and submitted to the testing repositories for Fedora and EPEL.
