### ISSUE TITLE
Remote sync via ssh

### ISSUE THREAD

**Issue by mvrhov** [martymac/fpart#2]
Sorry for writing a "support" question under an issue tracker, but I'm trying to speed up remote backup and which is atm run with the following command.

`rsync -avz -e "ssh -i /path/to/backup.key -p 1234" --delete /mnt/data/ archive@$DESTINATION::location/data/`

The archive user can only run rsync command
e,g. the authorized_keys_file looks like this:

```
command="rsync --config=/srv/archive/rsyncd.conf --server --daemon . /srv/archive/data",no-agent-forwarding,no-port-forwarding,no-user-rc,no-X11-forwarding,no-pty ssh-rsa  .....
```

and then the rsyncd.conf has a named sections one for each server

**Comment by martymac** [comment]
Hi,

If I try to "translate" your rsync call to a fpsync one, you could use the following :

$ fpsync -n 4 -E -o "-zlptgoD -v --numeric-ids" /mnt/data/ archive@$DESTINATION::location/data/

That will start 4 concurrent transfers and enable rsync's -z option. Option -E will enable directory mode (and thus the --delete option ; that can be avoided if you perform incremental backups only). 
You will have to set your SSH key and port through ssh' config file as fpsync does not allow to set SSH parameters.

Hope that helps,

Ganael.

**Comment by mvrhov** [comment]
Hi,

Is this something new that's supposed to work. I'm asking because v0.9.2, returns "Please supply an absolute path for both src_dir/ and dst_dir/"

**Comment by martymac** [comment]
Yes it is, but you have to update fpart/fpsync to 1.0.0 :
- support for rsync URLs has been added in 0.9.3
- support for parallelized --delete (option -E) has been added in 1.0.0

**Comment by mvrhov** [comment]
I've created the package for xenial for 1.0 and this still fails with the following error message 
`Please supply either an absolute path or a rsync URL for dst_url/`.

I'd guess that this doesn't like rsync named sections. See [examples section](https://download.samba.org/pub/rsync/rsyncd.conf.html).
This is the `::` designator instead of single `::`

**Comment by martymac** [comment]
Can you try with a rsync:// URL as target ?

Something like :
rsync://archive@$DESTINATION/location/data/

**Comment by martymac** [comment]
Regexp to detect remote path was erroneous. I've simplified it. Can you tell me if the following commit :
https://github.com/martymac/fpart/commit/b9faedc1594acc509b794ec674b9be509e42c715#diff-5834325afd283a2803c4ee69867e0fb0
fixes your problem ?

**Comment by mvrhov** [comment]
There is no error now. 
However I need to pass the -e parameter with ssh parameters to rsync otherwise the connection times out afaik this is the only way the rsync connection will go through ssh tunnel.
I've taken the command line from one of the batch files and added `-e "ssh -i /path/to/backup.key -p 1234"` to it and then it works.

**Comment by martymac** [comment]
Great!
Note that you could pass SSH parameters through fpsync's -o option too :
$ fpsync [...] -o "-zlptgoD -v --numeric-ids -e 'ssh -i /path/to/backup.key -p 1234'" [...]
as in that case, ssh is executed from rsync, not fpsync.

**Comment by martymac** [comment]
Great!

Note that my first answer could lead to confusion : " fpsync does not allow to set SSH parameters". Indeed, it does not allow to pass SSH parameters when sending jobs to SSH workers. But in your precise case, you were talking about forking SSH from rsync, so rsync options (fpsync's -o option) can be used for that :

$ fpsync [...] -o "-zlptgoD -v --numeric-ids -e 'ssh -i /path/to/backup.key -p 1234'" [...]

Regards,
Ganael.

**Comment by mvrhov** [comment]
Sorry to dissapoint you, but this doesn't work.  
The problem is that the `'` is not escaped when you generate the command to execute.
I've also tried to pass parameters with escaped double quotes however in such case you output everything to the command file without any quotes.

`$ fpsync [...] -o "-zlptgoD -v --numeric-ids -e \"ssh -i /path/to/backup.key -p 1234\"" [...]` no qoutes in output file
`$ fpsync [...] -o "-zlptgoD -v --numeric-ids -e ""ssh -i /path/to/backup.key -p 1234""" [...]` no qoutes in output file
`$ fpsync [...] -o "-zlptgoD -v --numeric-ids -e 'ssh -i /path/to/backup.key -p 1234'" [...]` single quotes, but unesaped as everytinh is wraped into single quotes on the outside for a sh parameter

**Comment by martymac** [comment]
Hmmm... Can you try with the following syntax :
-o "-zlptgoD -v --numeric-ids -e \\\"ssh -p 2234\\\""

**Comment by mvrhov** [comment]
I did try 3 syntaxes listed above. And provided the results. The one you suggested is amongst them.

**Comment by martymac** [comment]
I can only see a single backslash in your examples. Has it been escaped by GH ?

**Comment by mvrhov** [comment]
Oh. Sorry I did miss that. The triple one works.  IMO this should be added inside a readme, or even better, the fpsync should support `-e` (renamed if necessary) out of the box and add it properly to the final shell file as someone else will probably bump against the same issue.

THANKS! for the great tool an support!

**Comment by martymac** [comment]
You're welcome. Thanks for the suggestion, I'll see what I can do :)
