### ISSUE TITLE
Look for MAIL_BIN in fpsync only if OPT_MAIL is set

### ISSUE THREAD

**Issue by helgi** [martymac/fpart#20]
My system doesn't have `mail` resulting in `which: no mail in (/sbin:/bin:/usr/sbin:/usr/bin)` on every run; would be good to only look for `mail` if it is going to be used or silence it as checks are done later on in the code as well :)

**Comment by martymac** [comment]
Hello @helgi,

I have replaced calls to 'which' by calls to 'command -v', which should not emit error messages. Can you check that commit 27618ae824612c95ae59af69480812a7ad9e1067 fixes your problem ?

**Comment by helgi** [comment]
Looks good to me, thanks :) probably not required since it’s in a subshell already but would perhaps redirect errors to dev null
