### ISSUE TITLE
"please supply and absolute path" when it already is

### ISSUE THREAD

**Issue by clbarnes** [martymac/fpart#21]
Command:
```sh
fpsync -n 5 -f 1000 -o "-azh --info=progress2 --exclude 'lost+found'" /data2/ $USER@$REMOTE:/path/to/data2/
```

Error:
```
Please supply an absolute path for both src_dir/ and dst_dir/
```

**Comment by martymac** [comment]
Hello Chris,

What version of fpsync are you using ? Also, can you check that $USER and $REMOTE variables are expanded correctly by your shell ? What is the final -expanded- target you are syncing to ?

**Comment by martymac** [comment]
Closing this now, do not hesitate to re-open it if you need more help.

Best regards.
