### ISSUE TITLE
Feature request: Transmitted data size?

### ISSUE THREAD

**Issue by gamename** [martymac/fpart#24]
Hi Ganael,

At the end of a copy, I notice you put how long (in seconds) the copy process took.  That's really great. 

Would it also be possible to log how much data was copied?

Thanks,
-Tennis

**Comment by martymac** [comment]
Hello Tennis,

Thanks for your suggestion. It is not as easy as it seems as there are currently no file/size feedback from each generated partition. I'll see what I can do ASAP.

Best regards,
Ganael.

**Comment by gamename** [comment]
Thanks Ganael!

**Comment by martymac** [comment]
Hello Tennis,

Well, I won't have time to implement it right now so I have added that suggestion to the TODO file (and I'll close that request).

Thanks for your feedback,
Regards,

Ganael.

**Comment by gamename** [comment]
Np. Do the best you can.  

Thanks for telling us.
-T
