### ISSUE TITLE
Currently transferred data measurement?

### ISSUE THREAD

**Issue by gamename** [martymac/fpart#27]
Hi Ganael,

Is there any way to figure out how much data has been transferred while FPSync is running?  

For example, if I start a transfer of a 3TB volume, how can I tell after 3 hours how much has actually been sent?

Possible?

Thank you,
-Tennis

**Comment by martymac** [comment]
Hello Tennis,

You can see the current transfer status by sending a SIGINFO to fpsync (on FreeBSD this can, be done by pressing CTRL-T. On GNU/Linux, you can use the kill command to send it). It will display the number of partitions transferred so far, the number of partitions remaining, and estimated remaining time. It will *not* display data volumes, I keep the idea in mind as this is related to issue #24 

Best regards,

Ganael.

**Comment by gamename** [comment]
Hi Ganael,

I don't think GNU/Linux has a SIGINFO signal.

**Comment by martymac** [comment]
Hello Tennis,

signal(7) man page shows SIGINFO (29).

You can use it that way :

$ kill -29 <fpsync_pid>

Best regards,

Ganael.

**Comment by gamename** [comment]
Thanks!
