### ISSUE TITLE
List of files transferred & their sizes?

### ISSUE THREAD

**Issue by gamename** [martymac/fpart#28]
Hi Ganael,

A customer of ours has asked if there is any way to get a log from fpart/fpsync that will show what files were transferred and their sizes.  Is that possible?

Thank you, sir.
-T

**Comment by martymac** [comment]
Hello Tennis,

You won't be able to get a direct listing of files already transferred (fpsync does not provide that ability, file lists can be HUGE), but you can guess it by scripting something that compares :

```
/tmp/fpsync/queue/<job id>/<part number> (remaining partitions to transfer)
/tmp/fpsync/work/<job id>/<part number> (partitions already transferred)
```

while getting file lists from :

`/tmp/fpsync/parts/<job id>/<part number>`

Regarding transferred data size, this is probably related to issue #24. I've have not time to look at it yet (I am quite busy, any contribution is welcome :p).

Best regards,

Ganael.

**Comment by gamename** [comment]
Thanks Ganael.  I'll have a look.
-T
