### ISSUE TITLE
Single files support

### ISSUE THREAD

**Issue by d3dx9** [martymac/fpart#33]
Hi!

I'm currently using rsync to transfer multiple TB per day in single files. They are each around 100GB and have the problem that the destination only gets its fullspeed when it uses multiple connections (like what the application axel does for the web) so I found this which seems to be pretty interesting. 

Is it somehow possible to sync single files over the day?

**Comment by martymac** [comment]
Hello,

Yes, you can use fpsync to generate single-file partitions :

`$ fpsync -f 1 /src/ /dst/`

If used in conjunction with several sync jobs (-n x), you will be ably to sync x files in parallel.

Best regards,

Ganel.

**Comment by d3dx9** [comment]
Hi Ganel,

it actually says the Source directory doesn't exist.

(venv) root@34253A1:~# fpsync -f 1 /root/1GB.bin rsync://rsyncdaemon/plots/
Source directory does not exist (or is not a directory): /root/1GB.bin

Best,
Julian

**Comment by martymac** [comment]
Hello Julian,

Right, fpsync is designed to work with directories only. You would have to play with fpart options (through fpsync's '-O' switch) to include wanted files only (maybe something like -O '-y *.txt') from src dir. *But* there seem to be a unwanted expansion when passing the wildcard character to fpart. I'll check that and try to come with a fix ASAP.

Best regards,

Ganael.

**Comment by martymac** [comment]
Hello Julian,

I've just pushed a fix for that long-standing issue. Can you try something like :

`$ fpsync -f 1 -O '-y|*.bin' /root/ rsync://rsyncdaemon/plots/`

It will scan /root/ for files named *.bin and generate single-filed partitions.

I hope this will answer what you were looking for.

Best regards,
Ganael.

**Comment by martymac** [comment]
Closing for now, thanks again for your report!
