### ISSUE TITLE
fpart: incomplete partitions on sshfs

### ISSUE THREAD

**Issue by vali-um** [martymac/fpart#35]
Hello,

We are currently trying to use fpart on a mounted sshfs (part of libfuse) filesystem.
The filesystem contains about 11TB of data within over 10.000.000 directories across 15.000.000 files.
Running fpart produces parts until it hits a little over 1.000.000 files. after that it seems that all the directories look empty or unreadable to fpart as it just writes out the current levels directories, then one level up and so on.
I further discovered that some directories in the middle of the run have their subdirectories listed as empty which should have files in them.
as far as i can tell it is inconsistent for which directories this happens.
The commandline used is:
`fpart -f 1000000 -o debug_2.part -zz -vv <MOUNTPOINT>`
This was tested with version 1.4.0 packaged in debian bullseye and version 1.4.1 built from the github repo.
Building with the option --enable-debug does not reveal anything more to me, the output just shows `valid_file():` iterating over the same files and directories (which later appear empty).

Running fpart on the original filesystem on the other server (ext4) produces complete partitions as far as i can tell.

I'd be happy to do further debug work if you tell me what you need.

Cheers,
Valentin

**Comment by martymac** [comment]
Hello,

Can you crawl your SSHFS filesystem with something like :

$ find /path/to/sshfs -ls

to force stat()'ing every single file/dir ? Is crawling failing the same way ?

**Comment by martymac** [comment]
Hello Valentin,

> I have never seen such an error message, what format would this message have and are there circumstances which prevent those messages?

Nothing can normally prevent those messages from appearing. They are of the form:

<file_path>: <strerror(errno)>

See: https://github.com/martymac/fpart/blob/master/src/file_entry.c#L657
and: https://github.com/martymac/fpart/blob/master/src/utils.c#L169

> I straced the process [...]

The trace above clearly shows that fstat() on that directory does not return any error and reports a quite small directory (st_size=4096), probably an empty one. That suggests a silent failure of an underlying layer (SSHFS or Fuse itself).

Could you try to switch to embedded fts code to see how it behaves ? (use configure's --enable-embfts to enable it and then rebuild fpart).

**Comment by vali-um** [comment]
Hi Ganael,

I have, for sure, never seen such a message before...

Building with `--enable-embfts`  and running fpart on the sshfs filesystem doesn't fail silent as before but shows errors in the form of: `<file_path>: No such file or directory` for the subdirectories missing from the output list.

fpart output looks like this:
```
[....]
/mountpoint/XXX/development setup/subdir1: No such file or directory
/mountpoint/XXX/development setup/subdir2: No such file or directory
/mountpoint/XXX/development setup/subdir3: No such file or directory
/mountpoint/XXX/development setup/subdir4: No such file or directory
/mountpoint/XXX/development setup/subdir5: No such file or directory
/mountpoint/XXX/development setup/subdir6: No such file or directory
/mountpoint/XXX/development setup/subdir7: No such file or directory
/mountpoint/XXX/development setup/subdir8: No such file or directory
/mountpoint/XXX/development setup/subdir9: No such file or directory
/mountpoint/XXX/development setup/subdir10: No such file or directory
/mountpoint/XXX/development setup/subdir11: No such file or directory
/mountpoint/XXX/development setup/subdir12: No such file or directory
/mountpoint/XXX/development setup/subdir13: No such file or directory
/mountpoint/XXX/development setup/subdir14: No such file or directory
/mountpoint/XXX/development setup/subdir15: No such file or directory
/mountpoint/XXX/development setup: No such file or directory
[...]
```

while the corresponding strace output shows:
```
openat(AT_FDCWD, "development setup", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 4</mountpoint/XXX/development setup>
fstat(4</mountpoint/XXX/development setup>, {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
fstat(4</mountpoint/XXX/development setup>, {st_mode=S_IFDIR|S_ISGID|0775, st_size=4096, ...}) = 0
getdents64(4</mountpoint/XXX/development setup>, 0x556fe59df6e0 /* 17 entries */, 32768) = 608
getdents64(4</mountpoint/XXX/development setup>, 0x556fe59df6e0 /* 0 entries */, 32768) = 0
close(4</mountpoint/XXX/development setup>) = 0
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 88) = 88 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 81) = 81 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 81) = 81 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 81) = 81 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 94) = 94 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 94) = 94 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 77) = 77 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 80) = 80 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 100) = 100
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 83) = 83 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 81) = 81 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 96) = 96 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 96) = 96 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 78) = 78 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 81) = 81 
write(2</root/fpart_debug/fs_root_strace_embtfs.log>, "/mountpoint/XXX/devel"..., 72) = 72 
openat(AT_FDCWD, "..", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 4</mountpoint>
```

I'm still not sure what to make of this because `getdents64` seems to give the expected output but there are no following `newfstatat` calls (the behavior i could see on previous, correctly listed, directories)

I have to say, my understanding of fuse and the corresponding syscalls is extremely limited. If you are convinced that this is a failure in fuse/sshfs feel free to close this issue.
Otherwise I'd be happy to do more debugging.

Cheers, Valentin

**Comment by martymac** [comment]
Hello Valentin,

Thanks for your feedback.

Really seems like an underlying FS (SSHFS or FUSE) failure to me (getdsent() returning 17 enrtries, not reachable afterwards). If you want to get further (now that you can reproduce the problem with embedded fts), you could use gdb (rebuild fpart with --enable-debug) and try to see what stat calls are failing here.

I'll close that PR for the moment, feel free to re-open it if you need further help.

Best regards,

Ganael.
