### ISSUE TITLE
Status / percentage complete / progress bar?

### ISSUE THREAD

**Issue by ylluminate** [martymac/fpart#46]
Have you thought about a possible way to implement a percentage complete or an estimating completion progress bar?

**Comment by martymac** [comment]
Hello,

Thanks your suggestion.

About the progress bar, I'll keep that in mind when refactoring fpsync output (I don't think it would be easy to add with current output style).

About the % complete part, sending a SIGINFO (CTRL-T on FreeBSD) to the main fpsync process will display it.

Best regards,

Ganael.
