### ISSUE TITLE
How to sync local directory to a remote directory by fpsync

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [martymac/fpart#50]
Dear author!  I want to sync a local directory to a remote directory via ssh using fpsync, my command is as follows:
  fpsync -vv -n 8 -f 128 -t /data/public/alphafold2-2.3.1/tmp -o "-zlptgoD -v --numeric-ids -e \\\"ssh -i id_ecdsa -p 22 scx6001@ BSCC-N32-H@ssh.cn-zhongwei-1.paracloud.com \\\"" /data/public/alphafold2-2.3.1/ /home/bingxing2/public/alphafold2.3.2
The key file here is: id_ecdsa
Account name: scx6001@BSCC-N32-H
Domain name: ssh.cn-zhongwei-1.paracloud.com
source dir :/data/public/alphafold2-2.3.1/
destnation dir:/home/bingxing2/public/alphafold2.3.2
After execution, the following error will appear:
Cannot create destination directory: /home/bingxing2/public/alphafold2.3.2
How can I solve this problem? Looking forward to your reply.

**Comment by martymac** [comment]
Hello,

Please have a look at https://www.fpart.org/fpsync/#ssh-options. Fpsync target URL should be something like : login@remote:/data/dst/.

Also, check that your SSH user has write access to /home/bingxing2/public/ remote directory.

Best regards,

Ganael.
