### ISSUE TITLE
fpsync: job control error running under cron

### ISSUE THREAD

**Issue by JamesDarcy616** [martymac/fpart#51]
Hi Ganael

Is there any way to fix job control warnings when running under cron where there is no tty? My output is filled with errors like these:

`/usr/local/bin/fpsync: 1531: set: can't access tty; job control turned off`

one for each partition when `set -m` is called. fpsync seems to work still but the output is hard to see amidst the error spam.

Thanks

James

**Comment by martymac** [comment]
Hello James,

This is probably related to issue #43. See also :

https://patchwork.kernel.org/project/dash/patch/dedaa3fa370ea9c4aeb1771b5568a7bef4065b04.1675113321.git.steffen@sdaoden.eu/

Have you tried running fpsync with another shell (e.g. Bash) ?

**Comment by JamesDarcy616** [comment]
The crontab already had `SHELL=/bin/bash` so I changed fpsync's shebang to use `bash` not `sh` and that's fixed it.

Thank you :)

**Comment by martymac** [comment]
You're welcome :)
