### ISSUE TITLE
How to burn the partition content to DVD / Blu-ray?

### ISSUE THREAD

**Issue by amalgame21** [martymac/fpart#53]
In the menu:
```
     fpart -s 4724464025 -o music-parts /path/to/music ./*.mp3
             Produce partitions of 4.4 GB, containing music files from /path/to/music as well as
             MP3 files from current directory; with such a partition size, each partition content
             will be ready to be burnt to a DVD. Files music-parts.0 to music-parts.n, are
             generated as output.
```
However it does not specified compatible tools to burn to a DVD or write to a burnable ISO image.
I tried `mkisofs` with `-path-list`, but it does not preserve the directory tree, so it failed when two or more files with the same filename in different directories are present.

I think there should be some tools that are compatible to fpart when you wrote the menu.
Would you mind recommending some of them? Thanks!

**Comment by amalgame21** [comment]
Ask in discussion instead.

**Comment by martymac** [comment]
Hello,

Yes, feel free to open a discussion thread in the appropriate section.

Fpart will only produce file listings so you have to use a tool (or write a script) that will consume those lists and do whatever you want with the files. Fpsync uses several of those tools : rsync, cpio, tar. You could use them to stage your files in a temporary dir before creating and burning you ISO file from there.

Best regards,

Ganael.
