### ISSUE TITLE
having issues with excluding directories or files, macOS

### ISSUE THREAD

**Issue by fleetwoodmac** [martymac/fpart#59]
Hello, 

I am having issues excluding files or directories with Fpsync on macOS. downloaded and installed using `brew install fpart`  on macOS 13.6.1. 

example, I have a folder that looks like this:

<img width="227" alt="image" src="https://github.com/martymac/fpart/assets/69140036/edbd28c7-8238-491e-9c0c-a605f35641d6">

I have tried the syntax mentioned in this issue #17 to try and exclude, for example, any folders/files that mention 'pasta' using

- `fpsync -n 4 -o "--progress" -O '-X /pasta' ~/Test  /dest/path/`
- `fpsync -n 4 -o "--progress" -O '-X ./pasta' ~/Test  /dest/path/`
- `fpsync -n 4 -o "--progress" -O '-X *pasta*' ~/Test  /dest/path/`
- `fpsync -n 4 -o "--progress" -O "-X '*pasta*'"~/Test  /dest/path/`

I have tried just about every variation I could think of: double quotes, single quotes, quoting the pattern within portion that is feeding options to fpart, using -x instead of -X with all those variations, trying the ./ approach to get it to recognize a path, and I've tried different wildcard characters as it was stated those were supported as well. I have also tried excluding via the -o (feeding --exclude='whatever') to rsync, but I get an rsync 'action not supported' error in the the logs trying that. I confirmed that when using rsync itself, excludes work fine. Any help/guidance I could get would be appreciated.

**Comment by martymac** [comment]
Hello,

Sub-option passing has been reworked. Please try latest version from git repository and pass options that way :

`$ fpsync -n 4 [...] -O "-X|*pasta*" ~/Test  /dest/path/`

I just tried it with your file tree, it works for me :)

Best regards,

Ganael

**Comment by fleetwoodmac** [comment]
Worked, thank you! I have a few other questions, trying to learn this tool:
1. I was reading the docs/man page and the -zzz and -P flags for fpart were stated to be needed to correctly use cpio/tar. I am trying to experiment with rsync, and those other tools to see which will be best for many small files, but when I pass -O "-zzzP" or "-zzz -P", I get an illegal option error thrown. Was -P removed/what is the new command required to flush parent hierarchies?
2. What is the tarify tool? I cannot seem to find any other info about it, and I am kind of confused as to the definition given on the Fpart website.
3. Issues is probably not the best place to ask further questions...Do you have a preferred place for users to contact you with regard to questions about the tool?

**Comment by martymac** [comment]
Hello,

1. Those options still exist but -P is present in current git branch only. Be sure fpsync uses latest fpart binary. You may have to adapt FPART_BIN to avoid using your old version installed via brew (see: https://github.com/martymac/fpart/blob/master/tools/fpsync#L1099)
2. Tarify will create tar files in your destination directory, one per partition. You can then get your original filesystem by un-taring them all.
3. You can use the "discussions" tab on Github for such questions :)

Best regards (and happy new year),

Ganael.

**Comment by fleetwoodmac** [comment]
Awesome, thank you for the answers Ganael. Also please let me know if there is an anonymous way to donate. I don't see an option to do so in the paypal link in the readme.

**Comment by martymac** [comment]
Hello,

That's a very kind attention, thanks! Unfortunately, I think Paypal does not allow making anonymous donations. I still have to set up a Github sponsors page. If you prefer using that way, I'll let you know when it is up :)

Cheers,

Ganael.

**Comment by martymac** [comment]
Hello @fleetwoodmac,

Thanks for your patience. If you still wish to make a donation, my Github sponsors page is now live here:

https://github.com/sponsors/martymac?o=esb

I will update README file and main website to include that link.

Thanks again for your support!

Have a nice day,
Ganael.

**Comment by fleetwoodmac** [comment]
Hi Ganael,

Thanks for setting up a GitHub Sponsors page. Donated. Best of luck with development, will continue using this tool!

**Comment by martymac** [comment]
Hi @fleetwoodmac,

Thanks a lot! This is much appreciated, really :)

Have a nice day,

Ganael.
