### ISSUE TITLE
fpsync: Identify which file is currently processed (transfered)?

### ISSUE THREAD

**Issue by 74cmonty** [martymac/fpart#6]
Hi,

I'm using fpsync to transfer >1000 files from A to B via ssh.
Some of the files are >1TB, in fact the file size could be up to 10TB.

Question:
How can I identify which file(s) are currently processed in order to verify the process?

THX

**Comment by martymac** [comment]
Hi,

Fpsync can show you an overall status when pressing CTRL-T (or sending a SIGINFO to the process) but it will not show you then current *file(s)* being transferred. Only the external processes used to copy the partitions (rsync) have that piece of information.

Either study rsync processes' states (open fds and current file offsets) or have a look at the current jobs' logs within /tmp/fpsync/log/<jobid>/<partitionid>. As rsync is always started in verbose mode, you'll get the current files being transfered from there (stdout).

Note that starting fpsync in verbose mode will help you find the current <jobid> and <partitionid>.

Hope this helps,
Best regards,

Ganael.

**Comment by 74cmonty** [comment]
Hi,
I'm not sure how to identify the currently transferred files in my ongoing scenario.

So, this is the latest console output where fpsync is running:
```
=> [QMGR] Starting job /tmp/fpsync/work/1530709496-15795/100 (local)
=> [QMGR] Starting job /tmp/fpsync/work/1530709496-15795/101 (local)
<= [QMGR] Job 62960:local finished
=> [QMGR] Starting job /tmp/fpsync/work/1530709496-15795/102 (local)
<= [QMGR] Job 60346:local finished
=> [QMGR] Starting job /tmp/fpsync/work/1530709496-15795/103 (local)
<= [QMGR] Job 48693:local finished
=> [QMGR] Starting job /tmp/fpsync/work/1530709496-15795/104 (local)
<= [QMGR] Job 33561:local finished
<=== [QMGR] Done submitting jobs. Waiting for them to finish.

```
And this is the current content in _/tmp/fpsync/log/_:
```
ld4465:~ # ls -ltr /tmp/fpsync/log/
total 48
drwxr-xr-x 2 root root  4096 Jun 29 16:32 1530282563-66748
drwxr-xr-x 2 root root 12288 Jun 30 05:57 1530283048-50222
drwxr-xr-x 2 root root 12288 Jul  3 00:21 1530514541-2094
drwxr-xr-x 2 root root  4096 Jul  4 15:01 1530709238-66704
drwxr-xr-x 2 root root  4096 Jul  4 15:04 1530709317-76037
drwxr-xr-x 2 root root 12288 Jul  4 15:11 1530709496-15795

```
Checking the lastly created _1530709496-15795_ I get this:
[...]```

-rw-r--r-- 1 root root   134 Jul  4 15:10 101.stdout
-rw-r--r-- 1 root root     0 Jul  4 15:10 102.stderr
-rw-r--r-- 1 root root   396 Jul  4 15:10 102.stdout
-rw-r--r-- 1 root root     0 Jul  4 15:10 103.stdout
-rw-r--r-- 1 root root     0 Jul  4 15:10 103.stderr
-rw-r--r-- 1 root root     0 Jul  4 15:11 104.stdout
-rw-r--r-- 1 root root     0 Jul  4 15:11 104.stderr
-rw-r--r-- 1 root root 13916 Jul  4 15:11 fpart.log
-rw-r--r-- 1 root root   750 Jul  4 15:12 75.stdout
-rw-r--r-- 1 root root   186 Jul  4 19:40 8.stderr
-rw-r--r-- 1 root root   435 Jul  6 10:14 2.stderr
-rw-r--r-- 1 root root   474 Jul  6 11:51 7.stderr
-rw-r--r-- 1 root root   558 Jul  6 12:07 5.stderr
ld4465:~ #

```
The currently running rsync process is this:
```
ld4465:~ # ps -ef | grep 'rsync -s'
root     11777 39175  0 14:08 pts/2    00:00:00 grep --color=auto rsync -s
root     65618 65614 68 Jul04 pts/0    1-08:22:59 /usr/bin/rsync -s --numeric-ids -r --files-from=/tmp/fpsync/parts/1530709496-15795/part.104 --from0 /backup// cephosd1:/backup//

```
However the file _104.stdout_ is empty:
ld4465:~ # cat /tmp/fpsync/log/1530709496-15795/104.stdout
ld4465:~ #

**Comment by martymac** [comment]
You identified the right process, but it has not transferred anything yet as 
104.stdout is empty (rsync is always started in verbose mode so any transferred file should appear in that file).

You can try to run the rsync process by hand with the same arguments to see what happens (see the exact command in the /tmp/fpsync/work/1530709496-15795/104 file). 

You can also try to strace it to see what it is doing. Maybe you have a 
network-related problem (as the target is non-local) ?

Best regards,
Ganael.
