### ISSUE TITLE
using sshpass does not seem to work with fpsync

### ISSUE THREAD

**Issue by yghorbal** [martymac/fpart#60]
I'm trying to use sshpass for "reasons". This works out of the box:
`SSHPASS=somepassword sshpass -e rsync -av src/ user@server:dst/`

But when using fpsync it gets stuck in the ssh phase
`SSHPASS=somepassword sshpass -e fpsync -n 4 -f 3 src/ server:dst/`

parts are generated successefully, 4 rsync processes are started and subsequent 4 ssh processes but all of them are stuck in the `T` state (my guess that sshpass magic somehow stop to operate and ssh is waiting for user input)

Is there any way to use fpsync inside sshpass?

**Comment by yghorbal** [comment]
Hello @martymac, thank you for the quick reply. Just to be clear about my use case, I'm not trying to use sshpass for Fpsync SSH workers. I'm trying to use it only for the SSH session of Rsync itself.
I'll mess around with the script and see how things goes, and report back.

**Comment by yghorbal** [comment]
@martymac I've managed to make it work as I wanted
- create a simple shell script **rsync.sh**
```
#!/usr/bin/env bash
sshpass -e rsync "$@"
```
- run fpsync like this:
```
SSHPASS=somepassword fpsync -n 4 -f 3 -T /path/to/rsync.sh src/ server:dst/
```

**Comment by martymac** [comment]
Wow, perfect ! And thanks for your feedback :)

Cheers,

Ganael.
