### ISSUE TITLE
./configure issue on Linux Mint 21 and 21.3. (Ubunto 22.04)  Line 4145.

### ISSUE THREAD

**Issue by Eirikur** [martymac/fpart#62]
...
checking dependency style of cc... gcc3
./configure: line 4145: syntax error near unexpected token `newline'
./configure: line 4145: `    '''

I looked at the source code and I don't think you supply that line. I should be able to deal this with this, but I'm puzzled.
I thought I'd get  off the main branch in case this was a recent file corruption, but I don't see another branch that's current.
I've been thinking about writing something in this genre but it would make sense to adopt an existing solution!

Eirikur

**Comment by martymac** [comment]
Hello Eirikur,

Weird, I cannot reproduce the error myself as I don't use Linux Mint.

Have you tried to use autoreconf, as explained here: https://www.fpart.org/#installing-from-source ?

Cheers,

Ganael.

**Comment by Eirikur** [comment]
I'll get to that. I did play with autoreconf, but it got too late in the evening.
