### ISSUE TITLE
Is there a way to make FS crawl faster?

### ISSUE THREAD

**Issue by anetanel** [martymac/fpart#64]
I'm using fpsync (v1.6.1) to migrate a large volume (5.5TB, 26Mil files). 
Running `fpsync -p` takes around 145 minutes (and creates about 13k parts), while the sync itself takes only around 10 minutes at this stage.
The `files` and `size` parameters are default.
The underlying volume is an AWS gp3 SSD, capable of 16000 iops, but during the crawl it averages only around 2000 iops.
I already synced most of the data, and I'm using fpsync to sync the remainder, and would like to avoid the 2 hours+ of crawl time, during the final sync.

 
Is there something to do to improve the crawl stage? 
The filesystem is ext4, with mount options:(rw,relatime,data=ordered), and there is plenty of RAM/CPU power.

Thanks.

**Comment by martymac** [comment]
Hello Netanel,

The crawling stage is already ultra-fast as fpart uses lib fts which already embeds its own optimizations. Unfortunately, if you have many files, it can take a lot of time.

To save time, you may use fpsync's replay mode (option -R) to skip fpart crawling step. In replay mode, fpsync re-uses a run's partitions+scripts to re-do the sync. Please be aware that the *original* file lists are used in that mode, so it may be better to use it with option '-E' to work on a per-directory basis. If your file lists have not evolved, then you can just replay the run and it will update your file contents.

Best regards,

Ganael.
