### ISSUE TITLE
How can i speed up file transfers using fpsync?

### ISSUE THREAD

**Issue by Pendlers** [martymac/fpart#65]
Hello, 
  
  I'm preparing to migrate 10TB data. But I didn't get what I wanted to expect when I did the speed test. I find that fpsync is slower than rsync.

Env
- fpart v1.6.0
- fpsync v1.6.0
- 2c4g

Test dataset
- Total size: 49.8GB
- File count: 1.542 million
- Directory count: 205,575

```shell
src=/root/speed_test/docker/
dest=root@192.168.5.34:/tmp/docker

$ time fpsync -n $((`nproc`*8)) -f 100000 -vvv $src $dest
real    80m11.578s
user    75m27.755s
sys     22m34.384s


$ time rsync -aPz $src $dest
real    61m48.860s
user    6m13.303s
sys     3m6.101s
```

is there something wrong with the way I'm using it?

**Comment by martymac** [comment]
Hello,

`nproc`*8 seems a lot of parallel processes! If your underlying storage is not designed to parallelize IOs, you may be waiting here. Maybe try with less processes in parallel and compare run times by incrementing them (maybe start with 4 or 8 parallel processes ?)...

Merry Xmas,

Ganael.

**Comment by Pendlers** [comment]
Thanking you for your reply. I have achieved good results using fpsync in the cloud environment.

May you have the best Christmas ever.
