### ISSUE TITLE
autoconf build fails on RHEL/CentOS 6

### ISSUE THREAD

**Issue by survient** [martymac/fpart#7]
Trying to build fpart on RHEL6 and having issues:

+ autoreconf --install
configure.ac:1: error: Autoconf version 2.69 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63

**Comment by survient** [comment]
Thanks Ganael. I changed the AC_PREREQ in configure.ac to 2.63 and was able to get it to build. Is there a specific need to have 2.69 as the minimum autoconf version or would we be able to roll down the AC_PREREQ version? For el6 the base version of autoconf is 2.63 so it'd help keep the build process cleaner if that version could be used. Thanks

**Comment by martymac** [comment]
No there is no specific need for version 2.69. I have lowered the required autoconf version to 2.63.

Thanks for reporting that issue!

**Comment by survient** [comment]
No problem, this really helps with building clean RPMs, thanks again!

**Comment by martymac** [comment]
Great! Are you using the bundled .spec file or another one ? Don't hesitate to submit a pull request to update it if it does not fit your needs (the bundled one is quite old now).

Also, do you know if there are any chance of getting fpart included in RH repositories ?

**Comment by survient** [comment]
I can't say for sure but I'm at least taking the steps in that direction. First thing is getting something into COPR(done) and the next bit is some cleanup. One of my colleagues is a RHEL and Fedora-oriented package maintainer so they're helping me with the more gritty details. If we're looking at doing a pull request I'll have to work with my colleague to go through reviewing the openSUSE packaging guidelines since you've only got the one spec file upstream.

**Comment by martymac** [comment]
Yes, that would be nice to get the package integrated in RHEL :) Feel free to contact me again if you have any question or if you need help packaging it. Thanks for your interest in fpart!

**Comment by martymac** [comment]
FYI, I've just added a note about available packages. I've mentioned Copr for CentOS and Fedora packages. Thanks!

**Comment by survient** [comment]
> FYI, I've just added a note about available packages. I've mentioned Copr for CentOS and Fedora packages. Thanks!

Cool. Here is the current draft of the spec file I'm using for builds which is attempting to use Fedora packaging guidelines:

https://copr-dist-git.fedorainfracloud.org/cgit/survient/fpart/fpart.git/plain/fpart.spec?h=f28

It's leveraging the current snapshots so we'll need a release bump in order to clean it up further. I'll still need to spend some time working with my packaging colleague to figure out what this would look like for openSUSE to determine if we can use a shared spec file or if we'll need separate ones.

**Comment by martymac** [comment]
Great, thanks! I've updated the bundled sample .spec file.

I'll try to release a new version soon so that you can finalize the package.

Best regards,
Ganael.

**Comment by martymac** [comment]
Hello,

FYI, I have just tagged and released version 1.1.0 !

Best regards,

Ganael.

**Comment by survient** [comment]
Awesome. I'll do some touch-ups on my side and try to set up a proper release. Discussing with my packaging colleague it's probably best if we focus on COPR for Fedora and EPEL for now and possibly look at openSUSE at a later time if there's enough demand. I'll keep you posted.

**Comment by survient** [comment]
I've updated the COPR builds to 1.1.0 and have submitted a package review request for Fedora. We'll need a packaging "sponsor" to allow the package to be committed, but it can still be reviewed while we're awaiting a sponsor. If we're able to get a sponsor and approval for Fedora we can then move on to trying to get it submitted to EPEL(RHEL/CentOS 6/7) proper.

**Comment by martymac** [comment]
Good news, thanks! Just to be sure : have you thought about setting sudo, rsync and cpio dependencies to the package (they are required for fpsync) ?

**Comment by survient** [comment]
Does fpart call sudo internally? And is rsync and cpio required for both transfer modes?

**Comment by martymac** [comment]
Yep, fpsync can use sudo internally  (option -S) and can now use either rsync or cpio (option -m) ; at least one of those two tools is required.

**Comment by survient** [comment]
Fedora supports "weak" dependencies which I think is a good fit here: https://fedoraproject.org/wiki/Packaging:WeakDependencies I'm not sure if they'll work within EPEL but it's worth a shot.

**Comment by martymac** [comment]
Yes, it seems to be a good fit : that would allow one to install the package without installing rsync/cpio if the goal is to use fpart only (only fpsync requires sudo + fpsync or cpio).

**Comment by survient** [comment]
The package has been approved by a reviewer but still needs a Fedora sponsor before we can get further traction which I'm still searching for. I have an updated spec file here https://copr-be.cloud.fedoraproject.org/results/survient/fpart/srpm-builds/00826770/fpart.spec

**Comment by martymac** [comment]
Hi Samuel, Great! I've imported the new .spec file, thanks! Let's hope a sponsor approve the package too :)

**Comment by survient** [comment]
Hi Ganael. I saw your update on the bugzilla. My packaging colleague and I have not forgotten about the sponsorship requirement and are continually working to get through the red tape to get a sponsor, just to keep you in the loop.

**Comment by martymac** [comment]
Hi Samuel,
Good news, thanks for the update :)
